# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  
  - stage: Buildit
    jobs:  
    - deployment: VMDeploy
      displayName: web
      environment: 
        name:  dev
        resourceType: VirtualMachine
        tags: web1
      strategy:
        runOnce:
          deploy:    
            steps:
            - task: Maven@3
              inputs:
                mavenPomFile: 'pom.xml'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                testRunTitle: 'test'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.8'
                mavenVersionOption: 'Default'
                mavenOptions: '-Xmx3072m'
                mavenAuthenticateFeed: false
                effectivePomSkip: false
                sonarQubeRunAnalysis: false
                checkStyleRunAnalysis: true
